apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: kafka
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::401413892014:role/kafka-eks-project-dev-external-secrets-role
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: kafka