apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.producer.replicas }}
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: {{ .Values.imageRegistry }}/kafka-producer:{{ .Values.producer.imageTag }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers | quote }}
        - name: TOPIC_NAME
          value: {{ .Values.kafka.topicName | quote }}