apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kafka-consumer-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP