# Quick Guide:
# - Low traffic (<100 msg/sec): partitions: 3
# - Medium traffic (100-1000): partitions: 6
# - High traffic (>1000): partitions: 12
# - Always use replicas: 3

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic-name
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    min.insync.replicas: 2