# KafkaNodePool for broker nodes
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-brokers
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller  # Add controller role
  storage:
    type: persistent-claim
    size: 10Gi
    class: gp2
    deleteClaim: false
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
  jvmOptions:
    -Xms: 2048m
    -Xmx: 2048m
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - kafka
      tolerations:
      - key: "kafka"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"