watchNamespaces:
  - kafka

resources:
  limits:
    memory: 384Mi
    cpu: 1000m
  requests:
    memory: 384Mi
    cpu: 200m

logLevel: INFO

# Schedule operator on general nodes (not Kafka nodes)
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: workload
          operator: NotIn
          values:
          - kafka

# Allow running on any node (general nodes have no taints)
tolerations: []

labels:
  app: strimzi-operator